services:
  postgres:
    image: postgres:16
    container_name: photostockage-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: photostockage
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: photostockage-backend
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    env_file:
      - .env.docker

  frontend:
    build:
      context: ../photostockage
    container_name: photostockage-frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend

volumes:
  postgres_data:
    driver: local
